services:
  go-app:
    build: .
    container_name: tv2_go_backend
    environment:
      - DB_URL=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}
    networks:
      - tv2_backend_net
      - tv2_frontend_net
    restart: unless-stopped

networks:
  tv2_backend_net:
    external: true
  tv2_frontend_net:
    external: true
