// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/redis/go-redis/v9"
	"github.com/zerodayz7/http-server/config/env"
	"github.com/zerodayz7/http-server/internal/db"
	"github.com/zerodayz7/http-server/internal/handler"
	redis2 "github.com/zerodayz7/http-server/internal/redis"
	"github.com/zerodayz7/http-server/internal/repository/mysql"
	"github.com/zerodayz7/http-server/internal/repository/redis"
	"github.com/zerodayz7/http-server/internal/service"
	"github.com/zerodayz7/http-server/internal/shared/logger"
	"github.com/zerodayz7/http-server/internal/worker"
)

// Injectors from wire.go:

func InitializeInteractionModule(sqlDB *sql.DB, redisClient *redis.Client, cfg *env.Config, log logger.Logger) (*InteractionModule, error) {
	queries := db.New(sqlDB)
	mySQLInteractionRepo := mysql.NewInteractionRepository(queries)
	redisInteractionCache := redisrepo.NewRedisInteractionCache(redisClient)
	streamProducer := redis2.NewStreamProducer(redisClient)
	string2 := cfg.FingerprintSalt
	identityService := service.NewIdentityService(string2)
	interactionService := service.NewInteractionService(mySQLInteractionRepo, redisInteractionCache, streamProducer, identityService, log)
	interactionHandler := handler.NewInteractionHandler(interactionService)
	duration := cfg.Shutdown
	interactionWorker := worker.NewInteractionWorker(redisClient, mySQLInteractionRepo, log, duration)
	interactionModule := NewInteractionModule(interactionHandler, interactionWorker)
	return interactionModule, nil
}
