// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/redis/go-redis/v9"
	"github.com/zerodayz7/http-server/internal/db"
	"github.com/zerodayz7/http-server/internal/handler"
	"github.com/zerodayz7/http-server/internal/repository/mysql"
	"github.com/zerodayz7/http-server/internal/service"
)

// Injectors from wire.go:

func InitializeInteractionModule(sqlDB *sql.DB, redisClient *redis.Client) (*handler.InteractionHandler, error) {
	queries := db.New(sqlDB)
	mySQLInteractionRepo := mysql.NewInteractionRepository(queries)
	interactionService := service.NewInteractionService(mySQLInteractionRepo, redisClient)
	interactionHandler := handler.NewInteractionHandler(interactionService)
	return interactionHandler, nil
}
