// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IdentityService is an autogenerated mock type for the IdentityService type
type IdentityService struct {
	mock.Mock
}

// GenerateFingerprint provides a mock function with given fields: ip, ua, lang
func (_m *IdentityService) GenerateFingerprint(ip string, ua string, lang string) string {
	ret := _m.Called(ip, ua, lang)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFingerprint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(ip, ua, lang)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIdentityService creates a new instance of IdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityService {
	mock := &IdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
