// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/zerodayz7/http-server/internal/service"
)

// InteractionServiceInterface is an autogenerated mock type for the InteractionServiceInterface type
type InteractionServiceInterface struct {
	mock.Mock
}

// GenerateFingerprint provides a mock function with given fields: ip, ua, lang
func (_m *InteractionServiceInterface) GenerateFingerprint(ip string, ua string, lang string) string {
	ret := _m.Called(ip, ua, lang)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFingerprint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(ip, ua, lang)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetStats provides a mock function with given fields: ctx, fp
func (_m *InteractionServiceInterface) GetStats(ctx context.Context, fp string) (*service.StatsResponse, error) {
	ret := _m.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *service.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.StatsResponse, error)); ok {
		return rf(ctx, fp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.StatsResponse); ok {
		r0 = rf(ctx, fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleInteraction provides a mock function with given fields: ctx, fp, typ
func (_m *InteractionServiceInterface) HandleInteraction(ctx context.Context, fp string, typ string) (*service.StatsResponse, error) {
	ret := _m.Called(ctx, fp, typ)

	if len(ret) == 0 {
		panic("no return value specified for HandleInteraction")
	}

	var r0 *service.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*service.StatsResponse, error)); ok {
		return rf(ctx, fp, typ)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *service.StatsResponse); ok {
		r0 = rf(ctx, fp, typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fp, typ)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessInitialVisit provides a mock function with given fields: ctx, fp
func (_m *InteractionServiceInterface) ProcessInitialVisit(ctx context.Context, fp string) (*service.StatsResponse, error) {
	ret := _m.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for ProcessInitialVisit")
	}

	var r0 *service.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.StatsResponse, error)); ok {
		return rf(ctx, fp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.StatsResponse); ok {
		r0 = rf(ctx, fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInteractionServiceInterface creates a new instance of InteractionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteractionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *InteractionServiceInterface {
	mock := &InteractionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
