// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// InteractionCache is an autogenerated mock type for the InteractionCache type
type InteractionCache struct {
	mock.Mock
}

// GetGlobalCount provides a mock function with given fields: ctx, typ
func (_m *InteractionCache) GetGlobalCount(ctx context.Context, typ string) (int64, bool) {
	ret := _m.Called(ctx, typ)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalCount")
	}

	var r0 int64
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, bool)); ok {
		return rf(ctx, typ)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, typ)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, typ)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetUserChoice provides a mock function with given fields: ctx, fp
func (_m *InteractionCache) GetUserChoice(ctx context.Context, fp string) (string, bool, error) {
	ret := _m.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChoice")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, fp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, fp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, fp)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, fp)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetGlobalCount provides a mock function with given fields: ctx, typ, count, ttl
func (_m *InteractionCache) SetGlobalCount(ctx context.Context, typ string, count int64, ttl time.Duration) error {
	ret := _m.Called(ctx, typ, count, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetGlobalCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) error); ok {
		r0 = rf(ctx, typ, count, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TryRecordInteraction provides a mock function with given fields: ctx, fp, typ, cooldown
func (_m *InteractionCache) TryRecordInteraction(ctx context.Context, fp string, typ string, cooldown time.Duration) (bool, error) {
	ret := _m.Called(ctx, fp, typ, cooldown)

	if len(ret) == 0 {
		panic("no return value specified for TryRecordInteraction")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return rf(ctx, fp, typ, cooldown)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = rf(ctx, fp, typ, cooldown)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, fp, typ, cooldown)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TryRecordVisit provides a mock function with given fields: ctx, fp, cooldown
func (_m *InteractionCache) TryRecordVisit(ctx context.Context, fp string, cooldown time.Duration) (bool, error) {
	ret := _m.Called(ctx, fp, cooldown)

	if len(ret) == 0 {
		panic("no return value specified for TryRecordVisit")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return rf(ctx, fp, cooldown)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = rf(ctx, fp, cooldown)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, fp, cooldown)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInteractionCache creates a new instance of InteractionCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteractionCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *InteractionCache {
	mock := &InteractionCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
