// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/zerodayz7/http-server/internal/service"
)

// InteractionRepository is an autogenerated mock type for the InteractionRepository type
type InteractionRepository struct {
	mock.Mock
}

// GetStats provides a mock function with given fields: ctx
func (_m *InteractionRepository) GetStats(ctx context.Context) (service.InteractionStatsDTO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 service.InteractionStatsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.InteractionStatsDTO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.InteractionStatsDTO); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(service.InteractionStatsDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Increment provides a mock function with given fields: ctx, typ
func (_m *InteractionRepository) Increment(ctx context.Context, typ string) error {
	ret := _m.Called(ctx, typ)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, typ)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrementBy provides a mock function with given fields: ctx, typ, amount
func (_m *InteractionRepository) IncrementBy(ctx context.Context, typ string, amount int64) error {
	ret := _m.Called(ctx, typ, amount)

	if len(ret) == 0 {
		panic("no return value specified for IncrementBy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, typ, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInteractionRepository creates a new instance of InteractionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteractionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InteractionRepository {
	mock := &InteractionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
