// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package db

import (
	"context"
)

const getCountByType = `-- name: GetCountByType :one
SELECT current_count FROM interaction_stats 
WHERE type = ?
`

func (q *Queries) GetCountByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountByType, type_)
	var current_count int64
	err := row.Scan(&current_count)
	return current_count, err
}

const incrementCounter = `-- name: IncrementCounter :exec
UPDATE interaction_stats 
SET current_count = current_count + 1 
WHERE type = ?
`

func (q *Queries) IncrementCounter(ctx context.Context, type_ string) error {
	_, err := q.db.ExecContext(ctx, incrementCounter, type_)
	return err
}
