// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetCountByType(ctx context.Context, type_ string) (int64, error)
	IncrementCounter(ctx context.Context, type_ string) error
}

var _ Querier = (*Queries)(nil)
