// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetStats(ctx context.Context) (GetStatsRow, error)
	IncrementStat(ctx context.Context, type_ string) error
	IncrementStatByAmount(ctx context.Context, arg IncrementStatByAmountParams) error
}

var _ Querier = (*Queries)(nil)
