name: Go Docker Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Run Tests
        run: go test ./... -v

      - name: Generate .env file from Secrets
        run: |
          cat <<EOF > .env
          APP_NAME=${{ secrets.APP_NAME }}
          APP_VERSION=${{ secrets.APP_VERSION }}
          ENV=production
          PORT=${{ secrets.PORT }}
          SERVER_HEADER=${{ secrets.SERVER_HEADER }}

          PREFORK=${{ secrets.PREFORK }}
          CASE_SENSITIVE=${{ secrets.CASE_SENSITIVE }}
          STRICT_ROUTING=${{ secrets.STRICT_ROUTING }}
          BODY_LIMIT_MB=${{ secrets.BODY_LIMIT_MB }}

          IDLE_TIMEOUT_SEC=${{ secrets.IDLE_TIMEOUT_SEC }}
          READ_TIMEOUT_SEC=${{ secrets.READ_TIMEOUT_SEC }}
          WRITE_TIMEOUT_SEC=${{ secrets.WRITE_TIMEOUT_SEC }}
          SHUTDOWN_TIMEOUT_SEC=${{ secrets.SHUTDOWN_TIMEOUT_SEC }}

          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}

          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_DB=${{ secrets.REDIS_DB }}
          EOF

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            .
          target: "/home/${{ secrets.SERVER_USER }}/domains/backend/temp/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            BASE="${{ secrets.DEPLOY_PATH }}"

            mkdir -p $BASE/temp
            mkdir -p $BASE/production

            git pull origin main

            podman compose down
            podman compose up -d --build

            # opcjonalny health check
            sleep 5
            curl -f http://localhost:${{ secrets.PORT }}/health || exit 1
