name: Go Kubernetes Deployment

on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------
      # BUILD & PUSH API
      # -------------------
      - name: Build & Push API
        run: |
          IMAGE=ghcr.io/${{ vars.GHCR_OWNER }}/${{ vars.GHCR_IMAGE }}-api:${{ steps.vars.outputs.sha_short }}

          docker build \
            -t $IMAGE \
            -f cmd/api/Dockerfile \
            .

          docker push $IMAGE

      # -------------------
      # BUILD & PUSH WORKER (opcjonalnie)
      # -------------------
      # - name: Build & Push Worker
      #   run: |
      #     IMAGE=ghcr.io/${{ vars.GHCR_OWNER }}/${{ vars.GHCR_IMAGE }}-worker:${{ steps.vars.outputs.sha_short }}

      #     docker build \
      #       -t $IMAGE \
      #       -f cmd/worker/Dockerfile \
      #       .

      #     docker push $IMAGE

      # -------------------
      # KUBECONFIG
      # -------------------
      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      # -------------------
      # DEPLOY API
      # -------------------
      - name: Deploy API
        run: |
          IMAGE=ghcr.io/${{ vars.GHCR_OWNER }}/${{ vars.GHCR_IMAGE }}-api:${{ steps.vars.outputs.sha_short }}

          kubectl set image deployment/go-api \
            go-api=$IMAGE

          kubectl rollout status deployment/go-api

      # -------------------
      # DEPLOY WORKER (opcjonalnie)
      # -------------------
      # - name: Deploy Worker
      #   run: |
      #     IMAGE=ghcr.io/${{ vars.GHCR_OWNER }}/${{ vars.GHCR_IMAGE }}-worker:${{ steps.vars.outputs.sha_short }}

      #     kubectl set image deployment/go-worker \
      #       go-worker=$IMAGE

      #     kubectl rollout status deployment/go-worker
