apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: go-api
          image: ghcr.io/zerodayz7/http-server:9e7d7c7
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: api-config

          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: FINGERPRINT_SALT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FINGERPRINT_SALT

          volumeMounts:
            - name: migrations-dir
              mountPath: /app/migrations
              readOnly: true

      volumes:
        - name: migrations-dir
          configMap:
            name: api-migrations
