apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: go-api
          image: ghcr.io/zerodayz7/http-server-api:9e7d7c7
          ports:
            - containerPort: 9000

          # TUTAJ DODAŁEM volumeMounts
          volumeMounts:
            - name: migrations-dir
              mountPath: /app/migrations
              readOnly: true

          env:
            # DB connection
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database

            # Redis connection
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

      volumes:
        - name: migrations-dir
          configMap:
            name: api-migrations
